# note, when upgrading lts:
# $ stack build --copy-compiler-tool implicit-hie
# download new version of haskell-language-server -- see site for deets

resolver: lts-16.16
packages:
  - .
extra-deps:
  - implicit-hie-0.1.1.0
