name: hanabi
version: '0.1.0.0'
synopsis: Hanabi server and client
description: Please see the README on GitHub <github.com/anup-2s/haskell-gaming/blob/master/hanabi/README.md>
category: Web
author: Anup Kishore
maintainer: anup.kishore@gmail.com
copyright: 2017 Anup Kishore
# license: unlicensed
homepage: n/a
git: https://github.com/anup-2s/haskell-gaming

extra-source-files:
- README.md

dependencies:
- base >=4.7 && <5
- text >=1.2.2.0
- snap-core
- snap-server
- aeson
- text
- random
- random-shuffle
- containers
- split
- beam-core
- beam-postgres

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - MultiWayIf
  - TupleSections
  - DeriveGeneric
  - RankNTypes

library:
  source-dirs: lib

executables:
  hanabi-server:
    main: Main
    source-dirs: src
    ghc-options: [ -threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - hanabi

  hanabi-cli:
    main: Main
    source-dirs: cli
    ghc-options: [ -threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - hanabi
    - ansi-terminal
